tr_events = ["01_Mongolian",
          "02_Oxygen",
          "03_Lantern",
          "04_Snow Dragon Mountain",
          "05_Autumn",
          "06_Just You",
          "07_Misa",
          "08_Michelle",
          "09_Keep Your Head Down",
          "11_Basket",
          "12_Alice",
          "13_Watersleeves",
          "15_Umbrella",
          "16_Gary",
          "17_Sword",
          "18_Bang",
          "19_Boys",
          "20_Company",
          "21_Curtain Call",
          "24_Preshow"]